apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432  # access port of object in cluster
      targetPort: 5432  # access port of Deployment object (component: web)