apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379  # access port of object in cluster
      targetPort: 6379  # access port of Deployment object (component: web)